/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components.connexionv2;

import com.pradyna.main.ppe3;

/**
 *
 * @author pawel
 */
public class DialogFormConnexionv2 extends javax.swing.JDialog {

    com.pradyna.main.ppe3 objAutreFenetre = null;

    /**
     * Creates new form DialogFormConnexion
     */
    public DialogFormConnexionv2() {
        initComponents();
    }

    public DialogFormConnexionv2(com.pradyna.main.ppe3 fen) {
        this.objAutreFenetre = fen;
        initComponents();
        panneauFormConnexion.setFenParentConnexion(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauFormConnexion = new com.pradyna.components.connexionv2.PanneauFormConnexionv2();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauFormConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panneauFormConnexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ppe3 getObjAutreFenetre() {
        return objAutreFenetre;
    }

    public void setObjAutreFenetre(ppe3 objAutreFenetre) {
        this.objAutreFenetre = objAutreFenetre;
    }

    public PanneauFormConnexionv2 getPanneauFormConnexion() {
        return panneauFormConnexion;
    }

    public void setPanneauFormConnexion(PanneauFormConnexionv2 panneauFormConnexion) {
        this.panneauFormConnexion = panneauFormConnexion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pradyna.components.connexionv2.PanneauFormConnexionv2 panneauFormConnexion;
    // End of variables declaration//GEN-END:variables
}
