/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components.choixdossier;

import javax.swing.JPanel;

/**
 *
 * @author pawel
 */
public class DialogChoixDossier extends javax.swing.JDialog {

    javax.swing.JPanel objAutreFenetre = null;
    com.pradyna.main.ppe3 objAutreFenetreBis = null;

    /**
     * Creates new form DialogChoixFichierDossier
     */
    public DialogChoixDossier() {
        initComponents();
    }

    public DialogChoixDossier(javax.swing.JPanel fen) {
        this.objAutreFenetre = fen;
        initComponents();
        panneauChoixDossier.setPanneauPereChoixDossier(this);
    }

    public DialogChoixDossier(com.pradyna.main.ppe3 fen) {
        this.objAutreFenetreBis = fen;
        initComponents();
        panneauChoixDossier.setPanneauPereChoixDossier(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauChoixDossier = new com.pradyna.components.choixdossier.PanneauChoixDossier();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choix dossier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauChoixDossier, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauChoixDossier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PanneauChoixDossier getPanneauChoixDossier() {
        return panneauChoixDossier;
    }

    public void setPanneauChoixDossier(PanneauChoixDossier panneauChoixDossier) {
        this.panneauChoixDossier = panneauChoixDossier;
    }

    public JPanel getObjAutreFenetre() {
        return objAutreFenetre;
    }

    public void setObjAutreFenetre(JPanel objAutreFenetre) {
        this.objAutreFenetre = objAutreFenetre;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pradyna.components.choixdossier.PanneauChoixDossier panneauChoixDossier;
    // End of variables declaration//GEN-END:variables
}
