/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components.choixdossier;

import java.awt.Color;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author pawel
 */
public class PanneauChoixDossier extends javax.swing.JPanel {

    public JFileChooser jFileChooser;
    public File choix = null;

    private String formatFichier = null;
    private String donneesAExporter = null;
    private Boolean choixDossierOK = false;

    javax.swing.JDialog panneauPereChoixDossier = null;

    /**
     * Creates new form PanneauChoixFichierDossier
     */
    public PanneauChoixDossier() {
        initComponents();

        this.jFileChooser = new JFileChooser();
        this.jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        this.jFileChooser.setAcceptAllFileFilterUsed(false);
        this.jFileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File file) {
                return file.isDirectory();
            }

            @Override
            public String getDescription() {
                return "Dossier";
            }
        });

        jRadioButtonJSON.setActionCommand("JSON");
        jRadioButtonXML.setActionCommand("XML");
        jRadioButtonCSV.setActionCommand("CSV");
        jRadioButtonPDF.setActionCommand("PDF");

        buttonGroup.add(jRadioButtonJSON);
        buttonGroup.add(jRadioButtonXML);
        buttonGroup.add(jRadioButtonCSV);
        buttonGroup.add(jRadioButtonPDF);

        jRadioButtonTout.setActionCommand("Tout");
        jRadioButtonCompte.setActionCommand("Compte");
        jRadioButtonCV.setActionCommand("CV");

        buttonGroup1.add(jRadioButtonTout);
        buttonGroup1.add(jRadioButtonCompte);
        buttonGroup1.add(jRadioButtonCV);

        jRadioButtonJSON.setEnabled(false);
        jRadioButtonXML.setEnabled(false);
        jRadioButtonCSV.setEnabled(false);
        jRadioButtonPDF.setEnabled(false);
    }

    public JButton getjButtonValider() {
        return jButtonValider;
    }

    public JTextField getjTextFieldChemin() {
        return jTextFieldChemin;
    }

    public JDialog getPanneauPereChoixDossier() {
        return panneauPereChoixDossier;
    }

    public void setPanneauPereChoixDossier(JDialog panneauPereChoixDossier) {
        this.panneauPereChoixDossier = panneauPereChoixDossier;
    }

    public String getFormatFichier() {
        return formatFichier;
    }

    public String getDonneesAExporter() {
        return donneesAExporter;
    }

    public Boolean getChoixDossierOK() {
        return choixDossierOK;
    }

    public JRadioButton getjRadioButtonCSV() {
        return jRadioButtonCSV;
    }

    public JRadioButton getjRadioButtonJSON() {
        return jRadioButtonJSON;
    }

    public JRadioButton getjRadioButtonPDF() {
        return jRadioButtonPDF;
    }

    public JRadioButton getjRadioButtonXML() {
        return jRadioButtonXML;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtonChoisir = new javax.swing.JButton();
        jTextFieldChemin = new javax.swing.JTextField();
        jButtonValider = new javax.swing.JButton();
        jRadioButtonJSON = new javax.swing.JRadioButton();
        jRadioButtonXML = new javax.swing.JRadioButton();
        jRadioButtonCSV = new javax.swing.JRadioButton();
        jRadioButtonPDF = new javax.swing.JRadioButton();
        jLabelEtat = new javax.swing.JLabel();
        jRadioButtonTout = new javax.swing.JRadioButton();
        jRadioButtonCompte = new javax.swing.JRadioButton();
        jRadioButtonCV = new javax.swing.JRadioButton();

        jButtonChoisir.setText("Choisir dossier");
        jButtonChoisir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoisirActionPerformed(evt);
            }
        });

        jTextFieldChemin.setEditable(false);
        jTextFieldChemin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldChemin.setText("Aucun dossier sélectionné");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jRadioButtonJSON.setText("JSON");

        jRadioButtonXML.setText("XML");

        jRadioButtonCSV.setText("CSV");

        jRadioButtonPDF.setText("PDF");

        jLabelEtat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jRadioButtonTout.setText("Tout");
        jRadioButtonTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonToutActionPerformed(evt);
            }
        });

        jRadioButtonCompte.setText("Compte");
        jRadioButtonCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCompteActionPerformed(evt);
            }
        });

        jRadioButtonCV.setText("CV");
        jRadioButtonCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonValider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEtat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButtonJSON)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButtonXML)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButtonCSV))
                            .addComponent(jTextFieldChemin, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonChoisir)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButtonPDF)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jRadioButtonTout)
                .addGap(59, 59, 59)
                .addComponent(jRadioButtonCompte)
                .addGap(51, 51, 51)
                .addComponent(jRadioButtonCV)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonTout)
                    .addComponent(jRadioButtonCompte)
                    .addComponent(jRadioButtonCV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChoisir)
                    .addComponent(jTextFieldChemin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonJSON)
                    .addComponent(jRadioButtonXML)
                    .addComponent(jRadioButtonCSV)
                    .addComponent(jRadioButtonPDF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonValider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChoisirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoisirActionPerformed
        if (this.jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.choix = this.jFileChooser.getSelectedFile();
            jTextFieldChemin.setText(this.choix.getAbsolutePath());
            choixDossierOK = true;
        }
    }//GEN-LAST:event_jButtonChoisirActionPerformed

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        if (buttonGroup.getSelection() != null) {
            this.formatFichier = buttonGroup.getSelection().getActionCommand();
        } else {
            this.formatFichier = null;
        }

        if (buttonGroup1.getSelection() != null) {
            this.donneesAExporter = buttonGroup1.getSelection().getActionCommand();
        } else {
            this.donneesAExporter = null;
        }

        if (this.getDonneesAExporter() != null) {
            if (!this.getChoixDossierOK() && this.getFormatFichier() == null) {
                jLabelEtat.setForeground(Color.red);
                jLabelEtat.setText("Choix du dossier de destination et format du fichier manquants");
            } else if (!this.getChoixDossierOK() && this.getFormatFichier() != null) {
                jLabelEtat.setForeground(Color.red);
                jLabelEtat.setText("Choix du dossier de destination manquant");
            } else if (this.getChoixDossierOK() && this.getFormatFichier() == null) {
                jLabelEtat.setForeground(Color.red);
                jLabelEtat.setText("Choix du format du fichier manquant");
            }
        } else {
            jLabelEtat.setForeground(Color.red);
            jLabelEtat.setText("Choix des données à exporter manquant");
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jRadioButtonToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonToutActionPerformed
        updateButtonGroup1();
    }//GEN-LAST:event_jRadioButtonToutActionPerformed

    private void jRadioButtonCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCompteActionPerformed
        updateButtonGroup1();
    }//GEN-LAST:event_jRadioButtonCompteActionPerformed

    private void jRadioButtonCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCVActionPerformed
        updateButtonGroup1();
    }//GEN-LAST:event_jRadioButtonCVActionPerformed

    private void updateButtonGroup1() {
        if (buttonGroup1.getSelection() != null) {
            jRadioButtonJSON.setEnabled(true);
            jRadioButtonXML.setEnabled(true);
            jRadioButtonCSV.setEnabled(true);

            String actionCommand = buttonGroup1.getSelection().getActionCommand();

            if (actionCommand.equals("Tout")) {
                jRadioButtonPDF.setEnabled(true);
            } else {
                jRadioButtonPDF.setEnabled(false);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonChoisir;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabelEtat;
    private javax.swing.JRadioButton jRadioButtonCSV;
    private javax.swing.JRadioButton jRadioButtonCV;
    private javax.swing.JRadioButton jRadioButtonCompte;
    private javax.swing.JRadioButton jRadioButtonJSON;
    private javax.swing.JRadioButton jRadioButtonPDF;
    private javax.swing.JRadioButton jRadioButtonTout;
    private javax.swing.JRadioButton jRadioButtonXML;
    private javax.swing.JTextField jTextFieldChemin;
    // End of variables declaration//GEN-END:variables
}
