/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components.connexionmdp;

import com.pradyna.components.connexionmdp.PanneauConnexionMdp;
import com.pradyna.components.modification.PanneauFormModification;

/**
 *
 * @author pawel
 */
public class DialogFormConnexionMdp extends javax.swing.JDialog {

    com.pradyna.components.modification.PanneauFormModification objAutreFenetre = null;

    /**
     * Creates new form DialogFormConnexionMdp
     */
    public DialogFormConnexionMdp() {
        initComponents();
    }

    public DialogFormConnexionMdp(com.pradyna.components.modification.PanneauFormModification fen) {
        this.objAutreFenetre = fen;
        initComponents();
        panneauConnexionMdp1.setFenParentConnexion(this);
    }

    public PanneauFormModification getObjAutreFenetre() {
        return objAutreFenetre;
    }

    public void setObjAutreFenetre(PanneauFormModification objAutreFenetre) {
        this.objAutreFenetre = objAutreFenetre;
    }

    public PanneauConnexionMdp getPanneauConnexionMdp1() {
        return panneauConnexionMdp1;
    }

    public void setPanneauConnexionMdp1(PanneauConnexionMdp panneauConnexionMdp1) {
        this.panneauConnexionMdp1 = panneauConnexionMdp1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauConnexionMdp1 = new com.pradyna.components.connexionmdp.PanneauConnexionMdp();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauConnexionMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauConnexionMdp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pradyna.components.connexionmdp.PanneauConnexionMdp panneauConnexionMdp1;
    // End of variables declaration//GEN-END:variables
}
