/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components;

import com.karimandco.admin.PanneauAdministration;
import com.pradyna.main.ppe3;

/**
 *
 * @author pawel
 */
public class DialogAdministration extends javax.swing.JDialog {
    
    com.pradyna.main.ppe3 objAutreFenetre = null;

    /**
     * Creates new form DialogAdministration
     */
    public DialogAdministration() {
        initComponents();
    }
    
    public DialogAdministration(com.pradyna.main.ppe3 fen) {
        this.objAutreFenetre = fen;
        initComponents();
        panneauAdministration1.setFenParentAdministration(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauAdministration1 = new com.karimandco.admin.PanneauAdministration();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panneauAdministration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauAdministration1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ppe3 getObjAutreFenetre() {
        return objAutreFenetre;
    }
    
    public void setObjAutreFenetre(ppe3 objAutreFenetre) {
        this.objAutreFenetre = objAutreFenetre;
    }
    
    public PanneauAdministration getPanneauAdministration1() {
        return panneauAdministration1;
    }
    
    public void setPanneauAdministration1(PanneauAdministration panneauAdministration1) {
        this.panneauAdministration1 = panneauAdministration1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.karimandco.admin.PanneauAdministration panneauAdministration1;
    // End of variables declaration//GEN-END:variables
}
