/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components.connexion.all;

import com.pradyna.components.connexion.google.PanneauConnexionGoogle;
import com.pradyna.components.connexion.facebook.PanneauConnexionFacebook;

/**
 *
 * @author p.radyna
 */
public class PanneauConnexionAll extends javax.swing.JPanel {

    /**
     * Creates new form PanneauConnexionAll
     */
    public PanneauConnexionAll() {
        initComponents();
    }

    public PanneauConnexionFacebook getPanneauConnexionFacebook1() {
        return panneauConnexionFacebook1;
    }

    public PanneauConnexionGoogle getPanneauConnexionGoogle1() {
        return panneauConnexionGoogle1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauConnexionGoogle1 = new com.pradyna.components.connexion.google.PanneauConnexionGoogle();
        panneauConnexionFacebook1 = new com.pradyna.components.connexion.facebook.PanneauConnexionFacebook();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauConnexionGoogle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panneauConnexionFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panneauConnexionFacebook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panneauConnexionGoogle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pradyna.components.connexion.facebook.PanneauConnexionFacebook panneauConnexionFacebook1;
    private com.pradyna.components.connexion.google.PanneauConnexionGoogle panneauConnexionGoogle1;
    // End of variables declaration//GEN-END:variables
}
