/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.admin;

/**
 *
 * @author pawel
 */
public class DialogFormModification extends javax.swing.JDialog {

    com.karimandco.admin.PanneauAdministration objAutreFenetre = null;

    /**
     * Creates new form DialogFormModification
     */
    public DialogFormModification() {
        initComponents();
    }

    public DialogFormModification(com.karimandco.admin.PanneauAdministration fen) {
        this.objAutreFenetre = fen;
        initComponents();
        panneauFormModification1.setPanneauPereModification(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauFormModification1 = new com.karimandco.admin.PanneauFormModification();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauFormModification1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panneauFormModification1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public PanneauAdministration getObjAutreFenetre() {
        return objAutreFenetre;
    }

    public void setObjAutreFenetre(PanneauAdministration objAutreFenetre) {
        this.objAutreFenetre = objAutreFenetre;
    }

    public com.karimandco.admin.PanneauFormModification getPanneauFormModification1() {
        return panneauFormModification1;
    }

    public void setPanneauFormModification1(com.karimandco.admin.PanneauFormModification panneauFormModification1) {
        this.panneauFormModification1 = panneauFormModification1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.karimandco.admin.PanneauFormModification panneauFormModification1;
    // End of variables declaration//GEN-END:variables
}
