/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.cv;

import com.karimandco.bdd.DaoSIO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author pawel
 */
public class InformationComp extends javax.swing.JPanel {

    private Integer idInfoComp = null, idCV = null, idTab = null;

    /**
     * Creates new form InformationComp
     */
    public InformationComp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIntitulePartie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonSupprimeInfoComp = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informations complémentaires");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Intitulé de la catégorie");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Description");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jButtonSupprimeInfoComp.setText("x");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIntitulePartie)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSupprimeInfoComp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIntitulePartie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSupprimeInfoComp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * Cette methode crée les donnes de l'expérience professionnel dans la table
     * `experience_pro` et ensuite retourne l'id de la dernière occurence
     * inserer dans la table.
     *
     * @param args
     * @return Integer
     */
    public Integer setEnvoieInformationComp(Object... args) {
        Integer res, lastKey = null;

        Integer idCV = (Integer) args[0];

        String intitule = jTextFieldIntitulePartie.getText();

        if (!intitule.equals("")) {
            String description = jTextAreaDescription.getText();

            if (!description.equals("")) {
                if (DaoSIO.getInstance().connexionActive()) {
                    try {
                        if (this.idInfoComp != null) {
                            res = DaoSIO.getInstance().requeteAction("UPDATE `info_comp` "
                                    + "SET `intitule` = '" + intitule + "', `description` = '" + description + "'"
                                    + "WHERE id = " + this.idInfoComp);
                            lastKey = this.idInfoComp;
                        } else {
                            res = DaoSIO.getInstance().requeteAction("INSERT INTO `info_comp` (`intitule`, `description`, `id_cv`) "
                                    + "VALUES ('" + intitule + "', '" + description + "', '" + idCV + "');");
                            // Pour récupérer le dernière id de l'element 
                            lastKey = DaoSIO.getInstance().getLastID("info_comp", "id");
                            this.idInfoComp = lastKey;
                        }

                    } catch (SQLException ex) {
                        Logger.getLogger(ExperiencePro.class.getName()).log(Level.SEVERE, null, ex);
                        lastKey = null;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Veuillez saisir une description valide.", "Erreur Information complémentaires " + idTab, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez saisir un intitulé valide.", "Erreur Information complémentaires " + idTab, JOptionPane.ERROR_MESSAGE);
        }

        return lastKey;
    }

    public Integer getIdInfoComp() {
        return idInfoComp;
    }

    public void setIdInfoComp(Integer idInfoComp) {
        this.idInfoComp = idInfoComp;
    }

    public Integer getIdCV() {
        return idCV;
    }

    public void setIdCV(Integer idCV) {
        this.idCV = idCV;
    }

    public Integer getIdTab() {
        return idTab;
    }

    public void setIdTab(Integer idTab) {
        this.idTab = idTab;
    }

    public JTextArea getjTextAreaDescription() {
        return jTextAreaDescription;
    }

    public JTextField getjTextFieldIntitulePartie() {
        return jTextFieldIntitulePartie;
    }

    public JButton getjButtonSupprimeInfoComp() {
        return jButtonSupprimeInfoComp;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSupprimeInfoComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldIntitulePartie;
    // End of variables declaration//GEN-END:variables
}
