/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pradyna.components.modification;

import com.pradyna.components.modification.PanneauFormModification;
import com.pradyna.main.ppe3;

/**
 *
 * @author pawel
 */
public class DialogFormModification extends javax.swing.JDialog {

    com.pradyna.main.ppe3 objAutreFenetre = null;

    /**
     * Creates new form DialogFormModification
     */
    public DialogFormModification() {
        initComponents();
    }

    public DialogFormModification(com.pradyna.main.ppe3 fen) {
        this.objAutreFenetre = fen;
        initComponents();
        panneauFormModification1.setFenParentModification(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauFormModification1 = new com.pradyna.components.modification.PanneauFormModification();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panneauFormModification1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panneauFormModification1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ppe3 getObjAutreFenetre() {
        return objAutreFenetre;
    }

    public void setObjAutreFenetre(ppe3 objAutreFenetre) {
        this.objAutreFenetre = objAutreFenetre;
    }

    public PanneauFormModification getPanneauFormModification1() {
        return panneauFormModification1;
    }

    public void setPanneauFormModification1(PanneauFormModification panneauFormModification1) {
        this.panneauFormModification1 = panneauFormModification1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pradyna.components.modification.PanneauFormModification panneauFormModification1;
    // End of variables declaration//GEN-END:variables
}
